name: build games
on:
  push:
    branches:
      - main
permissions:
  contents: read
  packages: write
jobs:
  push:
    name: "games:${{ matrix.game }}"
    runs-on: ubuntu-22.04
    strategy:
      fail-fast: false
      matrix:
        game:
          - source
    steps:
      - uses: actions/checkout@v3
      - uses: docker/setup-buildx-action@v2
        with:
          buildkitd-flags: --debug
      - uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - uses: docker/build-push-action@v4
        with:
          context: ./${{ matrix.game }}
          file: ./${{ matrix.game }}/Dockerfile_Steam
          platforms: linux/amd64
          push: true
          tags: |
            ghcr.io/deff-dev/docker_images:${{ matrix.game }}-fix-cs2-update-proxy